-- MySQL Script generated by MySQL Workbench
-- qua 10 ago 2022 11:01:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`users` (
  `CPF` VARCHAR(11) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(35) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`contas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_CPF` VARCHAR(11) NOT NULL,
  `saldo` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_contas_users_idx` (`users_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_contas_users`
    FOREIGN KEY (`users_CPF`)
    REFERENCES `bank`.`users` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `bank`.`historic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank`.`historic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contas_id` INT UNSIGNED NOT NULL,
  `info` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `contas_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_historic_contas1_idx` (`contas_id` ASC) VISIBLE,
  CONSTRAINT `fk_historic_contas1`
    FOREIGN KEY (`contas_id`)
    REFERENCES `bank`.`contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
